In [20]:
#ques.1.
import numpy as np
a= np.random.rand(10,1)
print(a)
np.mean(a)

[[0.35036765]
 [0.99580788]
 [0.9533292 ]
 [0.31848466]
 [0.86886362]
 [0.05068733]
 [0.27209163]
 [0.0692974 ]
 [0.45483368]
 [0.10319186]]


0.4436954906280036

In [50]:
#ques.2.
import numpy as np
a= np.random.rand(20,1)
print(a)
c= np.var(a) 
print(c)
d= np.std(a)
print(d)


[[0.47163924]
 [0.13993007]
 [0.93958215]
 [0.11113591]
 [0.44441065]
 [0.90696976]
 [0.60908266]
 [0.5058505 ]
 [0.15794383]
 [0.20705697]
 [0.08668449]
 [0.52045275]
 [0.3358601 ]
 [0.12986052]
 [0.89258026]
 [0.29121203]
 [0.24022047]
 [0.69648092]
 [0.48152361]
 [0.64156877]]
0.07234734063330339
0.2689746096442997


In [70]:
#ques.3.
import numpy as np
a=np.random.rand(10,20)
b= np.random.rand(20,25)
mul = np.dot(a,b)
c= mul.shape
print(c)
d= np.sum(mul)
print(d)

(10, 25)
1278.7759947634145


In [75]:
#ques.4.
import numpy as np
np.arange(10).reshape(10,1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])